git:
  dags:
    enabled: true
    repositories:
    - repository: "https://github.com/peter-and-wolf/otus_mlops_k8s_dags.git"
      branch: "main"
      name: ""
      path: "dags"

extraEnvVars:
  - name: JOKE_API_URL
    value: "http://51.250.33.39:8000/api/v1/jokes"
